# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Podcast' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Podcast

	pod 'SwiftLint'
	pod 'Alamofire', '~> 4.5'
	pod 'SDWebImage', '~> 4.0'
	pod 'FeedKit', '~> 6.0'

  target 'PodcastTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PodcastUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
